version: "3.0"

services:

  db:
    image: postgres:9.6.12
    ports:
      - 7878:5432

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common

  webserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
      - tailwindcss
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
      - ./common:/app/common
  
  tailwindcss:
    build:
      context: ./frontend
      dockerfile: tailwind.Dockerfile
    volumes:
      - ./frontend:/app/frontend
    tty: true
