version: '3.4'

services:

  db:
    container_name: db
    image: postgres:9.6.12
    ports:
      - 7878:5432

  server:
    container_name: server
    build: 
      context: ./
      dockerfile: Dockerfile
    image: skarmux/cardcache
    depends_on:
      - db
    volumes:
      - ./backend:/opt/app/backend
      - ./common:/opt/app/common
    tty: true
    working_dir: /opt/app/backend
    # command: cargo run

  webserver:
    container_name: webserver
    image: skarmux/cardcache
    depends_on:
      - server
      - tailwindcss
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/opt/app/frontend
      - ./common:/opt/app/common
    tty: true
    working_dir: /opt/app/frontend
    command: trunk serve --release --watch tailwind.css
  
  tailwindcss:
    container_name: tailwindcss
    build:
      context: ./frontend
      dockerfile: tailwind.Dockerfile
    volumes:
      - ./frontend:/opt/app
    tty: true # allows --watch option to work
