version: '3.4'

services:

  db:
    image: postgres:9.6.12
    ports:
      - 7878:5432

  cardcache:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - tailwindcss
    volumes:
      - ./backend:/opt/app/backend
      - ./common:/opt/app/common
      - ./frontend:/opt/app/frontend

  # server:
  #   build:
  #     context: ./backend
  #     dockerfile: backend.Dockerfile
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/opt/app

  # webserver:
  #   build:
  #     context: ./frontend
  #     dockerfile: frontend.Dockerfile
  #   depends_on:
  #     - server
  #     - tailwindcss
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./frontend:/opt/app
  
  tailwindcss:
    build:
      context: ./frontend
      dockerfile: tailwind.Dockerfile
    volumes:
      - ./frontend:/opt/app
    tty: true # allows --watch option to work
